### ISSUE TITLE
Deterministic figures

### ISSUE THREAD

**Issue by rodluger** [palumbom/palumbo22#3]
The README mentions that

> Note that the Figures 4 through 7 are probabilistic and not deterministic, so tiny differenes in the exact data points/errors from the published article may be noticeable.

Can you set a fixed randomizer seed to help with this?

**Comment by rodluger** [comment]
Ah, I see -- the article is published already, and I imagine you didn't set one originally. Ignore me!

**Comment by palumbom** [comment]
Yep, I published this article first without showyourwork, and now I'm going back as an exercise for myself before getting too deep into my next paper. I figured their'd be a learning curve/maybe some weirdness with Julia vs. Python, so thanks for your help with everything :)
